# Utility script to download pinned data files and write their md5 checksums.
# Usage: Rscript scripts/fetch_data.R

source("R/config/constants.R")
source("R/utils/helpers.R")

ensure_dir(dirname(PWT11_LOCAL))
ensure_dir(dirname(MADDISON_LOCAL))

download_one <- function(url, dest) {
  message(sprintf("Downloading %s -> %s", url, dest))
  utils::download.file(url, destfile = dest, mode = "wb", quiet = FALSE)
}

targets <- list(
  list(url = PWT11_URL, dest = PWT11_LOCAL, key = PWT11_CHECKSUM_KEY),
  list(url = MADDISON_URL, dest = MADDISON_LOCAL, key = MADDISON_CHECKSUM_KEY)
)

invisible(lapply(targets, function(tgt) download_one(tgt$url, tgt$dest)))

checks <- vapply(targets, function(tgt) {
  hash <- unname(tools::md5sum(tgt$dest))
  sprintf("%s %s", tgt$key, hash)
}, character(1))

header <- c(
  "# MD5 checksums for pinned data files",
  "# Generated by scripts/fetch_data.R"
)

writeLines(c(header, checks), CHECKSUM_FILE)
message(sprintf("Checksums written to %s", CHECKSUM_FILE))
